language: node_js

node_js:
    - 'stable'

cache:
    directories:
        - 'node_modules'

install:
    - npm install -g automated-surge
    - npm install -g jsdoc

script:
    - ls
    - jsdoc -r modules
    - mv out documentation
    - automated-surge --project=./documentation --domain=circuitverse-docs.surge.sh
