language: node_js

node_js:
    - 'stable'

cache:
    directories:
        - 'node_modules'

install:
    - npm install -g surge
    - npm install -g jsdoc

script:
    - jsdoc -r modules ./README.md
    - mv out documentation
    - ls documentation

deploy:
    provider: surge
    project: ./documentation/
    domain: circuitverse-codebase-docs.surge.sh
